[2024-09-29T03:21:39.939+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-29T03:21:40.014+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2024-09-12T00:00:00+00:00 [queued]>
[2024-09-29T03:21:40.036+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2024-09-12T00:00:00+00:00 [queued]>
[2024-09-29T03:21:40.043+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-09-29T03:21:40.220+0000] {taskinstance.py:2888} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2024-09-12 00:00:00+00:00
[2024-09-29T03:21:40.281+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=18605) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-29T03:21:40.293+0000] {standard_task_runner.py:72} INFO - Started process 18621 to run task
[2024-09-29T03:21:40.267+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v04', 'insert_into_table', 'scheduled__2024-09-12T00:00:00+00:00', '--job-id', '359', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmpv9e227p3']
[2024-09-29T03:21:40.301+0000] {standard_task_runner.py:105} INFO - Job 359: Subtask insert_into_table
[2024-09-29T03:21:40.511+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2024-09-12T00:00:00+00:00 [running]> on host f9a59cccd6d1
[2024-09-29T03:21:41.003+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v04' AIRFLOW_CTX_TASK_ID='insert_into_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-12T00:00:00+00:00'
[2024-09-29T03:21:41.014+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-29T03:21:41.123+0000] {sql.py:266} INFO - Executing: 
            insert into dag_runs (dt, dag_id) values ('2024-09-12', 'dag_with_postgres_operator_v04')
            
[2024-09-29T03:21:41.164+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-29T03:21:41.185+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-29T03:21:41.196+0000] {sql.py:509} INFO - Running statement: 
            insert into dag_runs (dt, dag_id) values ('2024-09-12', 'dag_with_postgres_operator_v04')
            , parameters: None
[2024-09-29T03:21:41.211+0000] {sql.py:518} INFO - Rows affected: 1
[2024-09-29T03:21:41.271+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-29T03:21:41.281+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v04, task_id=insert_into_table, run_id=scheduled__2024-09-12T00:00:00+00:00, execution_date=20240912T000000, start_date=20240929T032140, end_date=20240929T032141
[2024-09-29T03:21:41.417+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-29T03:21:41.487+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-09-29T03:24:13.041+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-29T03:24:13.068+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2024-09-12T00:00:00+00:00 [queued]>
[2024-09-29T03:24:13.079+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2024-09-12T00:00:00+00:00 [queued]>
[2024-09-29T03:24:13.085+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-09-29T03:24:13.103+0000] {taskinstance.py:2888} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2024-09-12 00:00:00+00:00
[2024-09-29T03:24:13.127+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=18930) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-29T03:24:13.130+0000] {standard_task_runner.py:72} INFO - Started process 18936 to run task
[2024-09-29T03:24:13.127+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v04', 'insert_into_table', 'scheduled__2024-09-12T00:00:00+00:00', '--job-id', '405', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmpt9blaqoq']
[2024-09-29T03:24:13.137+0000] {standard_task_runner.py:105} INFO - Job 405: Subtask insert_into_table
[2024-09-29T03:24:13.201+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2024-09-12T00:00:00+00:00 [running]> on host f9a59cccd6d1
[2024-09-29T03:24:13.281+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v04' AIRFLOW_CTX_TASK_ID='insert_into_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-12T00:00:00+00:00'
[2024-09-29T03:24:13.282+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-29T03:24:13.299+0000] {sql.py:266} INFO - Executing: 
            insert into dag_runs (dt, dag_id) values ('2024-09-12', 'dag_with_postgres_operator_v04')
            
[2024-09-29T03:24:13.309+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-29T03:24:13.317+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-29T03:24:13.332+0000] {sql.py:509} INFO - Running statement: 
            insert into dag_runs (dt, dag_id) values ('2024-09-12', 'dag_with_postgres_operator_v04')
            , parameters: None
[2024-09-29T03:24:13.337+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 272, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 456, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "dag_runs_pkey"
DETAIL:  Key (dt, dag_id)=(2024-09-12, dag_with_postgres_operator_v04) already exists.

[2024-09-29T03:24:13.348+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_operator_v04, task_id=insert_into_table, run_id=scheduled__2024-09-12T00:00:00+00:00, execution_date=20240912T000000, start_date=20240929T032413, end_date=20240929T032413
[2024-09-29T03:24:13.360+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-29T03:24:13.363+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 405 for task insert_into_table (duplicate key value violates unique constraint "dag_runs_pkey"
DETAIL:  Key (dt, dag_id)=(2024-09-12, dag_with_postgres_operator_v04) already exists.
; 18936)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 272, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 456, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "dag_runs_pkey"
DETAIL:  Key (dt, dag_id)=(2024-09-12, dag_with_postgres_operator_v04) already exists.

[2024-09-29T03:24:13.397+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-29T03:24:13.406+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-09-29T03:26:52.997+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-29T03:26:53.034+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2024-09-12T00:00:00+00:00 [queued]>
[2024-09-29T03:26:53.056+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2024-09-12T00:00:00+00:00 [queued]>
[2024-09-29T03:26:53.059+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-09-29T03:26:53.131+0000] {taskinstance.py:2888} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2024-09-12 00:00:00+00:00
[2024-09-29T03:26:53.140+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=19234) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-29T03:26:53.141+0000] {standard_task_runner.py:72} INFO - Started process 19241 to run task
[2024-09-29T03:26:53.145+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v04', 'insert_into_table', 'scheduled__2024-09-12T00:00:00+00:00', '--job-id', '437', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmpipoknec6']
[2024-09-29T03:26:53.150+0000] {standard_task_runner.py:105} INFO - Job 437: Subtask insert_into_table
[2024-09-29T03:26:53.224+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2024-09-12T00:00:00+00:00 [running]> on host f9a59cccd6d1
[2024-09-29T03:26:53.298+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v04' AIRFLOW_CTX_TASK_ID='insert_into_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-12T00:00:00+00:00'
[2024-09-29T03:26:53.299+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-29T03:26:53.321+0000] {sql.py:266} INFO - Executing: 
            insert into dag_runs (dt, dag_id) values ('2024-09-12', 'dag_with_postgres_operator_v04')
            
[2024-09-29T03:26:53.330+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-29T03:26:53.337+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-29T03:26:53.345+0000] {sql.py:509} INFO - Running statement: 
            insert into dag_runs (dt, dag_id) values ('2024-09-12', 'dag_with_postgres_operator_v04')
            , parameters: None
[2024-09-29T03:26:53.351+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 272, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 456, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "dag_runs_pkey"
DETAIL:  Key (dt, dag_id)=(2024-09-12, dag_with_postgres_operator_v04) already exists.

[2024-09-29T03:26:53.359+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_operator_v04, task_id=insert_into_table, run_id=scheduled__2024-09-12T00:00:00+00:00, execution_date=20240912T000000, start_date=20240929T032653, end_date=20240929T032653
[2024-09-29T03:26:53.366+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-29T03:26:53.366+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 437 for task insert_into_table (duplicate key value violates unique constraint "dag_runs_pkey"
DETAIL:  Key (dt, dag_id)=(2024-09-12, dag_with_postgres_operator_v04) already exists.
; 19241)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 272, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 456, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "dag_runs_pkey"
DETAIL:  Key (dt, dag_id)=(2024-09-12, dag_with_postgres_operator_v04) already exists.

[2024-09-29T03:26:53.410+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-29T03:26:53.417+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1378 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2024-09-29T03:26:53.425+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-29T03:26:53.425+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-09-29T03:34:39.466+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-29T03:34:39.486+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2024-09-12T00:00:00+00:00 [queued]>
[2024-09-29T03:34:39.496+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2024-09-12T00:00:00+00:00 [queued]>
[2024-09-29T03:34:39.497+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-09-29T03:34:39.507+0000] {taskinstance.py:2888} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2024-09-12 00:00:00+00:00
[2024-09-29T03:34:39.541+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=19885) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-29T03:34:39.543+0000] {standard_task_runner.py:72} INFO - Started process 19888 to run task
[2024-09-29T03:34:39.533+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v04', 'insert_into_table', 'scheduled__2024-09-12T00:00:00+00:00', '--job-id', '470', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmp48vxn7_4']
[2024-09-29T03:34:39.548+0000] {standard_task_runner.py:105} INFO - Job 470: Subtask insert_into_table
[2024-09-29T03:34:39.599+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2024-09-12T00:00:00+00:00 [running]> on host f9a59cccd6d1
[2024-09-29T03:34:39.703+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v04' AIRFLOW_CTX_TASK_ID='insert_into_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-12T00:00:00+00:00'
[2024-09-29T03:34:39.703+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-29T03:34:39.717+0000] {sql.py:266} INFO - Executing: 
            insert into dag_runs (dt, dag_id) values ('2024-09-12', 'dag_with_postgres_operator_v04')
            
[2024-09-29T03:34:39.745+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-29T03:34:39.766+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-29T03:34:39.794+0000] {sql.py:509} INFO - Running statement: 
            insert into dag_runs (dt, dag_id) values ('2024-09-12', 'dag_with_postgres_operator_v04')
            , parameters: None
[2024-09-29T03:34:39.797+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 272, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 456, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "dag_runs_pkey"
DETAIL:  Key (dt, dag_id)=(2024-09-12, dag_with_postgres_operator_v04) already exists.

[2024-09-29T03:34:39.812+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_operator_v04, task_id=insert_into_table, run_id=scheduled__2024-09-12T00:00:00+00:00, execution_date=20240912T000000, start_date=20240929T033439, end_date=20240929T033439
[2024-09-29T03:34:39.839+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-29T03:34:39.840+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 470 for task insert_into_table (duplicate key value violates unique constraint "dag_runs_pkey"
DETAIL:  Key (dt, dag_id)=(2024-09-12, dag_with_postgres_operator_v04) already exists.
; 19888)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 272, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 456, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "dag_runs_pkey"
DETAIL:  Key (dt, dag_id)=(2024-09-12, dag_with_postgres_operator_v04) already exists.

[2024-09-29T03:34:39.860+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-29T03:34:39.879+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1378 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2024-09-29T03:34:39.893+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-29T03:34:39.894+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-09-29T03:37:45.715+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-29T03:37:45.762+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2024-09-12T00:00:00+00:00 [queued]>
[2024-09-29T03:37:45.782+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2024-09-12T00:00:00+00:00 [queued]>
[2024-09-29T03:37:45.791+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-09-29T03:37:45.849+0000] {taskinstance.py:2888} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2024-09-12 00:00:00+00:00
[2024-09-29T03:37:45.859+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=20194) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-29T03:37:45.860+0000] {standard_task_runner.py:72} INFO - Started process 20206 to run task
[2024-09-29T03:37:45.876+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v04', 'insert_into_table', 'scheduled__2024-09-12T00:00:00+00:00', '--job-id', '503', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmpccpx0m97']
[2024-09-29T03:37:45.891+0000] {standard_task_runner.py:105} INFO - Job 503: Subtask insert_into_table
[2024-09-29T03:37:46.017+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2024-09-12T00:00:00+00:00 [running]> on host f9a59cccd6d1
[2024-09-29T03:37:46.197+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v04' AIRFLOW_CTX_TASK_ID='insert_into_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-12T00:00:00+00:00'
[2024-09-29T03:37:46.203+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-29T03:37:46.238+0000] {sql.py:266} INFO - Executing: 
            insert into dag_runs (dt, dag_id) values ('2024-09-12', 'dag_with_postgres_operator_v04')
            
[2024-09-29T03:37:46.270+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-29T03:37:46.297+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-29T03:37:46.316+0000] {sql.py:509} INFO - Running statement: 
            insert into dag_runs (dt, dag_id) values ('2024-09-12', 'dag_with_postgres_operator_v04')
            , parameters: None
[2024-09-29T03:37:46.341+0000] {sql.py:518} INFO - Rows affected: 1
[2024-09-29T03:37:46.466+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-29T03:37:46.482+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v04, task_id=insert_into_table, run_id=scheduled__2024-09-12T00:00:00+00:00, execution_date=20240912T000000, start_date=20240929T033745, end_date=20240929T033746
[2024-09-29T03:37:46.588+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-29T03:37:46.689+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1378 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2024-09-29T03:37:46.757+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-29T03:37:46.761+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
