[2024-09-29T03:21:42.677+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-29T03:21:42.727+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v04.delete_from_table scheduled__2024-09-13T00:00:00+00:00 [queued]>
[2024-09-29T03:21:42.752+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v04.delete_from_table scheduled__2024-09-13T00:00:00+00:00 [queued]>
[2024-09-29T03:21:42.753+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-09-29T03:21:42.795+0000] {taskinstance.py:2888} INFO - Executing <Task(PostgresOperator): delete_from_table> on 2024-09-13 00:00:00+00:00
[2024-09-29T03:21:42.812+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=18657) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-29T03:21:42.818+0000] {standard_task_runner.py:72} INFO - Started process 18685 to run task
[2024-09-29T03:21:42.809+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v04', 'delete_from_table', 'scheduled__2024-09-13T00:00:00+00:00', '--job-id', '374', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmpa924yd47']
[2024-09-29T03:21:42.830+0000] {standard_task_runner.py:105} INFO - Job 374: Subtask delete_from_table
[2024-09-29T03:21:42.968+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_postgres_operator_v04.delete_from_table scheduled__2024-09-13T00:00:00+00:00 [running]> on host f9a59cccd6d1
[2024-09-29T03:21:43.088+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v04' AIRFLOW_CTX_TASK_ID='delete_from_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-13T00:00:00+00:00'
[2024-09-29T03:21:43.090+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-29T03:21:43.106+0000] {sql.py:266} INFO - Executing: 
            delete from dag_runs where dt = '2024-09-13' and dag_id='dag_with_postgres_operator_v04
            
[2024-09-29T03:21:43.115+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-29T03:21:43.121+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-29T03:21:43.129+0000] {sql.py:509} INFO - Running statement: 
            delete from dag_runs where dt = '2024-09-13' and dag_id='dag_with_postgres_operator_v04
            , parameters: None
[2024-09-29T03:21:43.135+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 272, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 456, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.SyntaxError: unterminated quoted string at or near "'dag_with_postgres_operator_v04
            "
LINE 2: ... from dag_runs where dt = '2024-09-13' and dag_id='dag_with_...
                                                             ^

[2024-09-29T03:21:43.143+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_operator_v04, task_id=delete_from_table, run_id=scheduled__2024-09-13T00:00:00+00:00, execution_date=20240913T000000, start_date=20240929T032142, end_date=20240929T032143
[2024-09-29T03:21:43.152+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-29T03:21:43.153+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 374 for task delete_from_table (unterminated quoted string at or near "'dag_with_postgres_operator_v04
            "
LINE 2: ... from dag_runs where dt = '2024-09-13' and dag_id='dag_with_...
                                                             ^
; 18685)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 272, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 456, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.SyntaxError: unterminated quoted string at or near "'dag_with_postgres_operator_v04
            "
LINE 2: ... from dag_runs where dt = '2024-09-13' and dag_id='dag_with_...
                                                             ^

[2024-09-29T03:21:43.191+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-29T03:21:43.207+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-29T03:21:43.208+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-09-29T03:37:47.976+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-29T03:37:48.002+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v04.delete_from_table scheduled__2024-09-13T00:00:00+00:00 [queued]>
[2024-09-29T03:37:48.016+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v04.delete_from_table scheduled__2024-09-13T00:00:00+00:00 [queued]>
[2024-09-29T03:37:48.020+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-09-29T03:37:48.045+0000] {taskinstance.py:2888} INFO - Executing <Task(PostgresOperator): delete_from_table> on 2024-09-13 00:00:00+00:00
[2024-09-29T03:37:48.061+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=20231) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-29T03:37:48.065+0000] {standard_task_runner.py:72} INFO - Started process 20245 to run task
[2024-09-29T03:37:48.065+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v04', 'delete_from_table', 'scheduled__2024-09-13T00:00:00+00:00', '--job-id', '515', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmpiomhmlmf']
[2024-09-29T03:37:48.077+0000] {standard_task_runner.py:105} INFO - Job 515: Subtask delete_from_table
[2024-09-29T03:37:48.155+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_postgres_operator_v04.delete_from_table scheduled__2024-09-13T00:00:00+00:00 [running]> on host f9a59cccd6d1
[2024-09-29T03:37:48.315+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v04' AIRFLOW_CTX_TASK_ID='delete_from_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-13T00:00:00+00:00'
[2024-09-29T03:37:48.319+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-29T03:37:48.346+0000] {sql.py:266} INFO - Executing: 
            delete from dag_runs where dt = '2024-09-13' and dag_id='dag_with_postgres_operator_v04'
            
[2024-09-29T03:37:48.368+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-29T03:37:48.385+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-29T03:37:48.398+0000] {sql.py:509} INFO - Running statement: 
            delete from dag_runs where dt = '2024-09-13' and dag_id='dag_with_postgres_operator_v04'
            , parameters: None
[2024-09-29T03:37:48.404+0000] {sql.py:518} INFO - Rows affected: 1
[2024-09-29T03:37:48.420+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-29T03:37:48.421+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v04, task_id=delete_from_table, run_id=scheduled__2024-09-13T00:00:00+00:00, execution_date=20240913T000000, start_date=20240929T033748, end_date=20240929T033748
[2024-09-29T03:37:48.435+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-29T03:37:48.453+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-29T03:37:48.461+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
