[2024-09-29T03:21:39.834+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-29T03:21:39.898+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2024-09-11T00:00:00+00:00 [queued]>
[2024-09-29T03:21:39.940+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2024-09-11T00:00:00+00:00 [queued]>
[2024-09-29T03:21:39.943+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-09-29T03:21:40.214+0000] {taskinstance.py:2888} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2024-09-11 00:00:00+00:00
[2024-09-29T03:21:40.243+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v04', 'insert_into_table', 'scheduled__2024-09-11T00:00:00+00:00', '--job-id', '357', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmp_tf1mmwu']
[2024-09-29T03:21:40.261+0000] {standard_task_runner.py:105} INFO - Job 357: Subtask insert_into_table
[2024-09-29T03:21:40.283+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=18602) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-29T03:21:40.293+0000] {standard_task_runner.py:72} INFO - Started process 18619 to run task
[2024-09-29T03:21:40.499+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2024-09-11T00:00:00+00:00 [running]> on host f9a59cccd6d1
[2024-09-29T03:21:41.061+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v04' AIRFLOW_CTX_TASK_ID='insert_into_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-11T00:00:00+00:00'
[2024-09-29T03:21:41.066+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-29T03:21:41.173+0000] {sql.py:266} INFO - Executing: 
            insert into dag_runs (dt, dag_id) values ('2024-09-11', 'dag_with_postgres_operator_v04')
            
[2024-09-29T03:21:41.213+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-29T03:21:41.296+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-29T03:21:41.315+0000] {sql.py:509} INFO - Running statement: 
            insert into dag_runs (dt, dag_id) values ('2024-09-11', 'dag_with_postgres_operator_v04')
            , parameters: None
[2024-09-29T03:21:41.322+0000] {sql.py:518} INFO - Rows affected: 1
[2024-09-29T03:21:41.372+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-29T03:21:41.378+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v04, task_id=insert_into_table, run_id=scheduled__2024-09-11T00:00:00+00:00, execution_date=20240911T000000, start_date=20240929T032139, end_date=20240929T032141
[2024-09-29T03:21:41.479+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-29T03:21:41.630+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1378 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2024-09-29T03:21:41.655+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-29T03:21:41.663+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-09-29T03:24:12.262+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-29T03:24:12.283+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2024-09-11T00:00:00+00:00 [queued]>
[2024-09-29T03:24:12.288+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2024-09-11T00:00:00+00:00 [queued]>
[2024-09-29T03:24:12.288+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-09-29T03:24:12.302+0000] {taskinstance.py:2888} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2024-09-11 00:00:00+00:00
[2024-09-29T03:24:12.314+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v04', 'insert_into_table', 'scheduled__2024-09-11T00:00:00+00:00', '--job-id', '399', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmpsgr02oy5']
[2024-09-29T03:24:12.316+0000] {standard_task_runner.py:105} INFO - Job 399: Subtask insert_into_table
[2024-09-29T03:24:12.318+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=18914) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-29T03:24:12.321+0000] {standard_task_runner.py:72} INFO - Started process 18916 to run task
[2024-09-29T03:24:12.418+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2024-09-11T00:00:00+00:00 [running]> on host f9a59cccd6d1
[2024-09-29T03:24:12.505+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v04' AIRFLOW_CTX_TASK_ID='insert_into_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-11T00:00:00+00:00'
[2024-09-29T03:24:12.506+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-29T03:24:12.549+0000] {sql.py:266} INFO - Executing: 
            insert into dag_runs (dt, dag_id) values ('2024-09-11', 'dag_with_postgres_operator_v04')
            
[2024-09-29T03:24:12.570+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-29T03:24:12.595+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-29T03:24:12.613+0000] {sql.py:509} INFO - Running statement: 
            insert into dag_runs (dt, dag_id) values ('2024-09-11', 'dag_with_postgres_operator_v04')
            , parameters: None
[2024-09-29T03:24:12.616+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 272, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 456, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "dag_runs_pkey"
DETAIL:  Key (dt, dag_id)=(2024-09-11, dag_with_postgres_operator_v04) already exists.

[2024-09-29T03:24:12.640+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_operator_v04, task_id=insert_into_table, run_id=scheduled__2024-09-11T00:00:00+00:00, execution_date=20240911T000000, start_date=20240929T032412, end_date=20240929T032412
[2024-09-29T03:24:12.737+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-29T03:24:12.737+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 399 for task insert_into_table (duplicate key value violates unique constraint "dag_runs_pkey"
DETAIL:  Key (dt, dag_id)=(2024-09-11, dag_with_postgres_operator_v04) already exists.
; 18916)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 272, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 456, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "dag_runs_pkey"
DETAIL:  Key (dt, dag_id)=(2024-09-11, dag_with_postgres_operator_v04) already exists.

[2024-09-29T03:24:12.795+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-29T03:24:12.860+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-09-29T03:26:52.748+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-29T03:26:52.784+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2024-09-11T00:00:00+00:00 [queued]>
[2024-09-29T03:26:52.858+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2024-09-11T00:00:00+00:00 [queued]>
[2024-09-29T03:26:52.864+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-09-29T03:26:52.959+0000] {taskinstance.py:2888} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2024-09-11 00:00:00+00:00
[2024-09-29T03:26:52.968+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=19231) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-29T03:26:52.971+0000] {standard_task_runner.py:72} INFO - Started process 19235 to run task
[2024-09-29T03:26:52.974+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v04', 'insert_into_table', 'scheduled__2024-09-11T00:00:00+00:00', '--job-id', '435', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmp9jgh82fv']
[2024-09-29T03:26:52.978+0000] {standard_task_runner.py:105} INFO - Job 435: Subtask insert_into_table
[2024-09-29T03:26:53.066+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2024-09-11T00:00:00+00:00 [running]> on host f9a59cccd6d1
[2024-09-29T03:26:53.119+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v04' AIRFLOW_CTX_TASK_ID='insert_into_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-11T00:00:00+00:00'
[2024-09-29T03:26:53.119+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-29T03:26:53.136+0000] {sql.py:266} INFO - Executing: 
            insert into dag_runs (dt, dag_id) values ('2024-09-11', 'dag_with_postgres_operator_v04')
            
[2024-09-29T03:26:53.147+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-29T03:26:53.157+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-29T03:26:53.171+0000] {sql.py:509} INFO - Running statement: 
            insert into dag_runs (dt, dag_id) values ('2024-09-11', 'dag_with_postgres_operator_v04')
            , parameters: None
[2024-09-29T03:26:53.179+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 272, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 456, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "dag_runs_pkey"
DETAIL:  Key (dt, dag_id)=(2024-09-11, dag_with_postgres_operator_v04) already exists.

[2024-09-29T03:26:53.194+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_operator_v04, task_id=insert_into_table, run_id=scheduled__2024-09-11T00:00:00+00:00, execution_date=20240911T000000, start_date=20240929T032652, end_date=20240929T032653
[2024-09-29T03:26:53.267+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-29T03:26:53.267+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 435 for task insert_into_table (duplicate key value violates unique constraint "dag_runs_pkey"
DETAIL:  Key (dt, dag_id)=(2024-09-11, dag_with_postgres_operator_v04) already exists.
; 19235)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 272, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 456, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "dag_runs_pkey"
DETAIL:  Key (dt, dag_id)=(2024-09-11, dag_with_postgres_operator_v04) already exists.

[2024-09-29T03:26:53.281+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-29T03:26:53.300+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1378 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2024-09-29T03:26:53.309+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-29T03:26:53.312+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-09-29T03:34:38.071+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-29T03:34:38.136+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2024-09-11T00:00:00+00:00 [queued]>
[2024-09-29T03:34:38.159+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2024-09-11T00:00:00+00:00 [queued]>
[2024-09-29T03:34:38.163+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-09-29T03:34:38.211+0000] {taskinstance.py:2888} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2024-09-11 00:00:00+00:00
[2024-09-29T03:34:38.226+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v04', 'insert_into_table', 'scheduled__2024-09-11T00:00:00+00:00', '--job-id', '466', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmp078urabb']
[2024-09-29T03:34:38.244+0000] {standard_task_runner.py:105} INFO - Job 466: Subtask insert_into_table
[2024-09-29T03:34:38.230+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=19870) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-29T03:34:38.249+0000] {standard_task_runner.py:72} INFO - Started process 19880 to run task
[2024-09-29T03:34:38.344+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2024-09-11T00:00:00+00:00 [running]> on host f9a59cccd6d1
[2024-09-29T03:34:38.429+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v04' AIRFLOW_CTX_TASK_ID='insert_into_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-11T00:00:00+00:00'
[2024-09-29T03:34:38.433+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-29T03:34:38.456+0000] {sql.py:266} INFO - Executing: 
            insert into dag_runs (dt, dag_id) values ('2024-09-11', 'dag_with_postgres_operator_v04')
            
[2024-09-29T03:34:38.467+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-29T03:34:38.487+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-29T03:34:38.509+0000] {sql.py:509} INFO - Running statement: 
            insert into dag_runs (dt, dag_id) values ('2024-09-11', 'dag_with_postgres_operator_v04')
            , parameters: None
[2024-09-29T03:34:38.514+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 272, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 456, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "dag_runs_pkey"
DETAIL:  Key (dt, dag_id)=(2024-09-11, dag_with_postgres_operator_v04) already exists.

[2024-09-29T03:34:38.552+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_operator_v04, task_id=insert_into_table, run_id=scheduled__2024-09-11T00:00:00+00:00, execution_date=20240911T000000, start_date=20240929T033438, end_date=20240929T033438
[2024-09-29T03:34:38.574+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-29T03:34:38.576+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 466 for task insert_into_table (duplicate key value violates unique constraint "dag_runs_pkey"
DETAIL:  Key (dt, dag_id)=(2024-09-11, dag_with_postgres_operator_v04) already exists.
; 19880)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 272, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 456, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "dag_runs_pkey"
DETAIL:  Key (dt, dag_id)=(2024-09-11, dag_with_postgres_operator_v04) already exists.

[2024-09-29T03:34:38.608+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-29T03:34:38.625+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1378 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2024-09-29T03:34:38.634+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-29T03:34:38.637+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-09-29T03:37:45.723+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-29T03:37:45.778+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2024-09-11T00:00:00+00:00 [queued]>
[2024-09-29T03:37:45.796+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2024-09-11T00:00:00+00:00 [queued]>
[2024-09-29T03:37:45.803+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-09-29T03:37:45.852+0000] {taskinstance.py:2888} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2024-09-11 00:00:00+00:00
[2024-09-29T03:37:45.867+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v04', 'insert_into_table', 'scheduled__2024-09-11T00:00:00+00:00', '--job-id', '504', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmppso7b3u9']
[2024-09-29T03:37:45.869+0000] {standard_task_runner.py:105} INFO - Job 504: Subtask insert_into_table
[2024-09-29T03:37:45.877+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=20190) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-29T03:37:45.896+0000] {standard_task_runner.py:72} INFO - Started process 20207 to run task
[2024-09-29T03:37:46.011+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_postgres_operator_v04.insert_into_table scheduled__2024-09-11T00:00:00+00:00 [running]> on host f9a59cccd6d1
[2024-09-29T03:37:46.311+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v04' AIRFLOW_CTX_TASK_ID='insert_into_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-11T00:00:00+00:00'
[2024-09-29T03:37:46.324+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-29T03:37:46.502+0000] {sql.py:266} INFO - Executing: 
            insert into dag_runs (dt, dag_id) values ('2024-09-11', 'dag_with_postgres_operator_v04')
            
[2024-09-29T03:37:46.583+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-29T03:37:46.634+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-29T03:37:46.650+0000] {sql.py:509} INFO - Running statement: 
            insert into dag_runs (dt, dag_id) values ('2024-09-11', 'dag_with_postgres_operator_v04')
            , parameters: None
[2024-09-29T03:37:46.659+0000] {sql.py:518} INFO - Rows affected: 1
[2024-09-29T03:37:46.694+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-29T03:37:46.697+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v04, task_id=insert_into_table, run_id=scheduled__2024-09-11T00:00:00+00:00, execution_date=20240911T000000, start_date=20240929T033745, end_date=20240929T033746
[2024-09-29T03:37:46.795+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-29T03:37:46.836+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1378 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2024-09-29T03:37:46.866+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-29T03:37:46.870+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
