[2024-09-29T03:21:41.087+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-29T03:21:41.150+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v04.delete_from_table scheduled__2024-09-07T00:00:00+00:00 [queued]>
[2024-09-29T03:21:41.175+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v04.delete_from_table scheduled__2024-09-07T00:00:00+00:00 [queued]>
[2024-09-29T03:21:41.184+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-09-29T03:21:41.293+0000] {taskinstance.py:2888} INFO - Executing <Task(PostgresOperator): delete_from_table> on 2024-09-07 00:00:00+00:00
[2024-09-29T03:21:41.357+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=18629) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-29T03:21:41.363+0000] {standard_task_runner.py:72} INFO - Started process 18644 to run task
[2024-09-29T03:21:41.338+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v04', 'delete_from_table', 'scheduled__2024-09-07T00:00:00+00:00', '--job-id', '365', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmpzqyl0nwx']
[2024-09-29T03:21:41.365+0000] {standard_task_runner.py:105} INFO - Job 365: Subtask delete_from_table
[2024-09-29T03:21:41.474+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_postgres_operator_v04.delete_from_table scheduled__2024-09-07T00:00:00+00:00 [running]> on host f9a59cccd6d1
[2024-09-29T03:21:41.828+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v04' AIRFLOW_CTX_TASK_ID='delete_from_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-07T00:00:00+00:00'
[2024-09-29T03:21:41.834+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-29T03:21:41.929+0000] {sql.py:266} INFO - Executing: 
            delete from dag_runs where dt = '2024-09-07' and dag_id='dag_with_postgres_operator_v04
            
[2024-09-29T03:21:42.043+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-29T03:21:42.189+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-29T03:21:42.236+0000] {sql.py:509} INFO - Running statement: 
            delete from dag_runs where dt = '2024-09-07' and dag_id='dag_with_postgres_operator_v04
            , parameters: None
[2024-09-29T03:21:42.242+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 272, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 456, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.SyntaxError: unterminated quoted string at or near "'dag_with_postgres_operator_v04
            "
LINE 2: ... from dag_runs where dt = '2024-09-07' and dag_id='dag_with_...
                                                             ^

[2024-09-29T03:21:42.302+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_operator_v04, task_id=delete_from_table, run_id=scheduled__2024-09-07T00:00:00+00:00, execution_date=20240907T000000, start_date=20240929T032141, end_date=20240929T032142
[2024-09-29T03:21:42.334+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-29T03:21:42.336+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 365 for task delete_from_table (unterminated quoted string at or near "'dag_with_postgres_operator_v04
            "
LINE 2: ... from dag_runs where dt = '2024-09-07' and dag_id='dag_with_...
                                                             ^
; 18644)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 272, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 456, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 514, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.SyntaxError: unterminated quoted string at or near "'dag_with_postgres_operator_v04
            "
LINE 2: ... from dag_runs where dt = '2024-09-07' and dag_id='dag_with_...
                                                             ^

[2024-09-29T03:21:42.398+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-29T03:21:42.525+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-29T03:21:42.547+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-09-29T03:37:46.301+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-29T03:37:46.433+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v04.delete_from_table scheduled__2024-09-07T00:00:00+00:00 [queued]>
[2024-09-29T03:37:46.493+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v04.delete_from_table scheduled__2024-09-07T00:00:00+00:00 [queued]>
[2024-09-29T03:37:46.498+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-09-29T03:37:46.585+0000] {taskinstance.py:2888} INFO - Executing <Task(PostgresOperator): delete_from_table> on 2024-09-07 00:00:00+00:00
[2024-09-29T03:37:46.642+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=20204) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-29T03:37:46.650+0000] {standard_task_runner.py:72} INFO - Started process 20219 to run task
[2024-09-29T03:37:46.638+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v04', 'delete_from_table', 'scheduled__2024-09-07T00:00:00+00:00', '--job-id', '508', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmp50u4kwvq']
[2024-09-29T03:37:46.651+0000] {standard_task_runner.py:105} INFO - Job 508: Subtask delete_from_table
[2024-09-29T03:37:46.770+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_postgres_operator_v04.delete_from_table scheduled__2024-09-07T00:00:00+00:00 [running]> on host f9a59cccd6d1
[2024-09-29T03:37:46.940+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator_v04' AIRFLOW_CTX_TASK_ID='delete_from_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-07T00:00:00+00:00'
[2024-09-29T03:37:46.942+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-29T03:37:46.956+0000] {sql.py:266} INFO - Executing: 
            delete from dag_runs where dt = '2024-09-07' and dag_id='dag_with_postgres_operator_v04'
            
[2024-09-29T03:37:46.970+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-29T03:37:46.984+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-29T03:37:47.003+0000] {sql.py:509} INFO - Running statement: 
            delete from dag_runs where dt = '2024-09-07' and dag_id='dag_with_postgres_operator_v04'
            , parameters: None
[2024-09-29T03:37:47.007+0000] {sql.py:518} INFO - Rows affected: 1
[2024-09-29T03:37:47.028+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-29T03:37:47.030+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v04, task_id=delete_from_table, run_id=scheduled__2024-09-07T00:00:00+00:00, execution_date=20240907T000000, start_date=20240929T033746, end_date=20240929T033747
[2024-09-29T03:37:47.055+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-29T03:37:47.067+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-29T03:37:47.068+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
